<?php
/**
 * NetworkList
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server Payment API
 *
 * RESTful API for payments via optile Open Payment Gateway (OPG) for server to server communication. Calls to this API require authorization.  ## Current version   * API service version: `1.1.289`   * API model version: `1.20.87`
 *
 * OpenAPI spec version: 1.1.289
 * Contact: support@optile.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Optile\Model;

use \ArrayAccess;
use \Optile\ObjectSerializer;

/**
 * NetworkList Class Doc Comment
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NetworkList implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'NetworkList';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'links' => '\Optile\Model\ListLinks',
        'timestamp' => '\DateTime',
        'operation' => 'string',
        'result_code' => 'string',
        'result_info' => 'string',
        'return_code' => '\Optile\Model\ReturnCode',
        'status' => '\Optile\Model\Status',
        'interaction' => '\Optile\Model\Interaction',
        'identification' => '\Optile\Model\Identification',
        'accounts' => '\Optile\Model\AccountRegistration[]',
        'networks' => '\Optile\Model\Networks',
        'extra_elements' => '\Optile\Model\ExtraElements',
        'redirect' => '\Optile\Model\Redirect',
        'preset_account' => '\Optile\Model\PresetAccount',
        'operation_type' => 'string',
        'allow_delete' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'links' => null,
        'timestamp' => 'date-time',
        'operation' => null,
        'result_code' => null,
        'result_info' => null,
        'return_code' => null,
        'status' => null,
        'interaction' => null,
        'identification' => null,
        'accounts' => null,
        'networks' => null,
        'extra_elements' => null,
        'redirect' => null,
        'preset_account' => null,
        'operation_type' => null,
        'allow_delete' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'links' => 'links',
        'timestamp' => 'timestamp',
        'operation' => 'operation',
        'result_code' => 'resultCode',
        'result_info' => 'resultInfo',
        'return_code' => 'returnCode',
        'status' => 'status',
        'interaction' => 'interaction',
        'identification' => 'identification',
        'accounts' => 'accounts',
        'networks' => 'networks',
        'extra_elements' => 'extraElements',
        'redirect' => 'redirect',
        'preset_account' => 'presetAccount',
        'operation_type' => 'operationType',
        'allow_delete' => 'allowDelete'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'links' => 'setLinks',
        'timestamp' => 'setTimestamp',
        'operation' => 'setOperation',
        'result_code' => 'setResultCode',
        'result_info' => 'setResultInfo',
        'return_code' => 'setReturnCode',
        'status' => 'setStatus',
        'interaction' => 'setInteraction',
        'identification' => 'setIdentification',
        'accounts' => 'setAccounts',
        'networks' => 'setNetworks',
        'extra_elements' => 'setExtraElements',
        'redirect' => 'setRedirect',
        'preset_account' => 'setPresetAccount',
        'operation_type' => 'setOperationType',
        'allow_delete' => 'setAllowDelete'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'links' => 'getLinks',
        'timestamp' => 'getTimestamp',
        'operation' => 'getOperation',
        'result_code' => 'getResultCode',
        'result_info' => 'getResultInfo',
        'return_code' => 'getReturnCode',
        'status' => 'getStatus',
        'interaction' => 'getInteraction',
        'identification' => 'getIdentification',
        'accounts' => 'getAccounts',
        'networks' => 'getNetworks',
        'extra_elements' => 'getExtraElements',
        'redirect' => 'getRedirect',
        'preset_account' => 'getPresetAccount',
        'operation_type' => 'getOperationType',
        'allow_delete' => 'getAllowDelete'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const OPERATION__LIST = 'LIST';
    const OPERATION_TYPE_CHARGE = 'CHARGE';
    const OPERATION_TYPE_PAYOUT = 'PAYOUT';
    const OPERATION_TYPE_PRESET = 'PRESET';
    const OPERATION_TYPE_UPDATE = 'UPDATE';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOperationAllowableValues()
    {
        return [
            self::OPERATION__LIST,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOperationTypeAllowableValues()
    {
        return [
            self::OPERATION_TYPE_CHARGE,
            self::OPERATION_TYPE_PAYOUT,
            self::OPERATION_TYPE_PRESET,
            self::OPERATION_TYPE_UPDATE,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['links'] = isset($data['links']) ? $data['links'] : null;
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['operation'] = isset($data['operation']) ? $data['operation'] : null;
        $this->container['result_code'] = isset($data['result_code']) ? $data['result_code'] : null;
        $this->container['result_info'] = isset($data['result_info']) ? $data['result_info'] : null;
        $this->container['return_code'] = isset($data['return_code']) ? $data['return_code'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['interaction'] = isset($data['interaction']) ? $data['interaction'] : null;
        $this->container['identification'] = isset($data['identification']) ? $data['identification'] : null;
        $this->container['accounts'] = isset($data['accounts']) ? $data['accounts'] : null;
        $this->container['networks'] = isset($data['networks']) ? $data['networks'] : null;
        $this->container['extra_elements'] = isset($data['extra_elements']) ? $data['extra_elements'] : null;
        $this->container['redirect'] = isset($data['redirect']) ? $data['redirect'] : null;
        $this->container['preset_account'] = isset($data['preset_account']) ? $data['preset_account'] : null;
        $this->container['operation_type'] = isset($data['operation_type']) ? $data['operation_type'] : null;
        $this->container['allow_delete'] = isset($data['allow_delete']) ? $data['allow_delete'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['links'] === null) {
            $invalidProperties[] = "'links' can't be null";
        }
        if ($this->container['timestamp'] === null) {
            $invalidProperties[] = "'timestamp' can't be null";
        }
        if ($this->container['operation'] === null) {
            $invalidProperties[] = "'operation' can't be null";
        }
        $allowedValues = $this->getOperationAllowableValues();
        if (!is_null($this->container['operation']) && !in_array($this->container['operation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'operation', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['result_code'] === null) {
            $invalidProperties[] = "'result_code' can't be null";
        }
        if ($this->container['result_info'] === null) {
            $invalidProperties[] = "'result_info' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['interaction'] === null) {
            $invalidProperties[] = "'interaction' can't be null";
        }
        if ($this->container['identification'] === null) {
            $invalidProperties[] = "'identification' can't be null";
        }
        $allowedValues = $this->getOperationTypeAllowableValues();
        if (!is_null($this->container['operation_type']) && !in_array($this->container['operation_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'operation_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets links
     *
     * @return \Optile\Model\ListLinks
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Optile\Model\ListLinks $links links
     *
     * @return $this
     */
    public function setLinks($links)
    {
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime $timestamp Date and time this `LIST` session was initialized at.
     *
     * @return $this
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets operation
     *
     * @return string
     */
    public function getOperation()
    {
        return $this->container['operation'];
    }

    /**
     * Sets operation
     *
     * @param string $operation Type of this operation
     *
     * @return $this
     */
    public function setOperation($operation)
    {
        $allowedValues = $this->getOperationAllowableValues();
        if (!in_array($operation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'operation', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['operation'] = $operation;

        return $this;
    }

    /**
     * Gets result_code
     *
     * @return string
     */
    public function getResultCode()
    {
        return $this->container['result_code'];
    }

    /**
     * Sets result_code
     *
     * @param string $result_code Result code of this `LIST` session. See list of all [Result Codes](https://www.optile.io/opg#294007).
     *
     * @return $this
     */
    public function setResultCode($result_code)
    {
        $this->container['result_code'] = $result_code;

        return $this;
    }

    /**
     * Gets result_info
     *
     * @return string
     */
    public function getResultInfo()
    {
        return $this->container['result_info'];
    }

    /**
     * Sets result_info
     *
     * @param string $result_info Descriptive information that complements the result code and interaction advice.
     *
     * @return $this
     */
    public function setResultInfo($result_info)
    {
        $this->container['result_info'] = $result_info;

        return $this;
    }

    /**
     * Gets return_code
     *
     * @return \Optile\Model\ReturnCode
     */
    public function getReturnCode()
    {
        return $this->container['return_code'];
    }

    /**
     * Sets return_code
     *
     * @param \Optile\Model\ReturnCode $return_code return_code
     *
     * @return $this
     */
    public function setReturnCode($return_code)
    {
        $this->container['return_code'] = $return_code;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Optile\Model\Status
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Optile\Model\Status $status Current status of this `LIST` session. See list of all [Status Codes](https://www.optile.io/opg#285186).
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets interaction
     *
     * @return \Optile\Model\Interaction
     */
    public function getInteraction()
    {
        return $this->container['interaction'];
    }

    /**
     * Sets interaction
     *
     * @param \Optile\Model\Interaction $interaction Interaction advice for this `LIST` session according to its current state.
     *
     * @return $this
     */
    public function setInteraction($interaction)
    {
        $this->container['interaction'] = $interaction;

        return $this;
    }

    /**
     * Gets identification
     *
     * @return \Optile\Model\Identification
     */
    public function getIdentification()
    {
        return $this->container['identification'];
    }

    /**
     * Sets identification
     *
     * @param \Optile\Model\Identification $identification identification
     *
     * @return $this
     */
    public function setIdentification($identification)
    {
        $this->container['identification'] = $identification;

        return $this;
    }

    /**
     * Gets accounts
     *
     * @return \Optile\Model\AccountRegistration[]
     */
    public function getAccounts()
    {
        return $this->container['accounts'];
    }

    /**
     * Sets accounts
     *
     * @param \Optile\Model\AccountRegistration[] $accounts Collection of registered accounts (if available) for recurring customer.
     *
     * @return $this
     */
    public function setAccounts($accounts)
    {
        $this->container['accounts'] = $accounts;

        return $this;
    }

    /**
     * Gets networks
     *
     * @return \Optile\Model\Networks
     */
    public function getNetworks()
    {
        return $this->container['networks'];
    }

    /**
     * Sets networks
     *
     * @param \Optile\Model\Networks $networks networks
     *
     * @return $this
     */
    public function setNetworks($networks)
    {
        $this->container['networks'] = $networks;

        return $this;
    }

    /**
     * Gets extra_elements
     *
     * @return \Optile\Model\ExtraElements
     */
    public function getExtraElements()
    {
        return $this->container['extra_elements'];
    }

    /**
     * Sets extra_elements
     *
     * @param \Optile\Model\ExtraElements $extra_elements extra_elements
     *
     * @return $this
     */
    public function setExtraElements($extra_elements)
    {
        $this->container['extra_elements'] = $extra_elements;

        return $this;
    }

    /**
     * Gets redirect
     *
     * @return \Optile\Model\Redirect
     */
    public function getRedirect()
    {
        return $this->container['redirect'];
    }

    /**
     * Sets redirect
     *
     * @param \Optile\Model\Redirect $redirect If present, merchant is advised to redirect customer to corresponding redirect URL. In case of `HOSTED` integration scenario this will lead customer to payment page hosted by optile.
     *
     * @return $this
     */
    public function setRedirect($redirect)
    {
        $this->container['redirect'] = $redirect;

        return $this;
    }

    /**
     * Gets preset_account
     *
     * @return \Optile\Model\PresetAccount
     */
    public function getPresetAccount()
    {
        return $this->container['preset_account'];
    }

    /**
     * Sets preset_account
     *
     * @param \Optile\Model\PresetAccount $preset_account preset_account
     *
     * @return $this
     */
    public function setPresetAccount($preset_account)
    {
        $this->container['preset_account'] = $preset_account;

        return $this;
    }

    /**
     * Gets operation_type
     *
     * @return string
     */
    public function getOperationType()
    {
        return $this->container['operation_type'];
    }

    /**
     * Sets operation_type
     *
     * @param string $operation_type Types of operation what could been triggered by `LIST` session.
     *
     * @return $this
     */
    public function setOperationType($operation_type)
    {
        $allowedValues = $this->getOperationTypeAllowableValues();
        if (!is_null($operation_type) && !in_array($operation_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'operation_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['operation_type'] = $operation_type;

        return $this;
    }

    /**
     * Gets allow_delete
     *
     * @return bool
     */
    public function getAllowDelete()
    {
        return $this->container['allow_delete'];
    }

    /**
     * Sets allow_delete
     *
     * @param bool $allow_delete Indicates that deletion of registered accounts is allowed in scope of this `LIST` session:   * If set to `true` the deletion accounts is explicitly permitted by merchant.   * If set to `false` the deletion accounts is explicitly disallowed by merchant.   * If nothing is set the default behavior applies: deletion is only allowed for `LIST`s in the `updateOnly` mode.
     *
     * @return $this
     */
    public function setAllowDelete($allow_delete)
    {
        $this->container['allow_delete'] = $allow_delete;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


