<?php
/**
 * ApplicableNetworkTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server Payment API
 *
 * RESTful API for payments via optile Open Payment Gateway (OPG) for server to server communication. Calls to this API require authorization.  ## Current version   * API service version: `1.1.289`   * API model version: `1.20.87`
 *
 * OpenAPI spec version: 1.1.289
 * Contact: support@optile.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optile;

/**
 * ApplicableNetworkTest Class Doc Comment
 *
 * @category    Class
 * @description ApplicableNetwork
 * @package     Optile
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ApplicableNetworkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ApplicableNetwork"
     */
    public function testApplicableNetwork()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }

    /**
     * Test attribute "method"
     */
    public function testPropertyMethod()
    {
    }

    /**
     * Test attribute "grouping"
     */
    public function testPropertyGrouping()
    {
    }

    /**
     * Test attribute "registration"
     */
    public function testPropertyRegistration()
    {
    }

    /**
     * Test attribute "recurrence"
     */
    public function testPropertyRecurrence()
    {
    }

    /**
     * Test attribute "redirect"
     */
    public function testPropertyRedirect()
    {
    }

    /**
     * Test attribute "button"
     */
    public function testPropertyButton()
    {
    }

    /**
     * Test attribute "selected"
     */
    public function testPropertySelected()
    {
    }

    /**
     * Test attribute "contract_data"
     */
    public function testPropertyContractData()
    {
    }

    /**
     * Test attribute "form_data"
     */
    public function testPropertyFormData()
    {
    }

    /**
     * Test attribute "i_frame_height"
     */
    public function testPropertyIFrameHeight()
    {
    }

    /**
     * Test attribute "empty_form"
     */
    public function testPropertyEmptyForm()
    {
    }

    /**
     * Test attribute "localized_input_elements"
     */
    public function testPropertyLocalizedInputElements()
    {
    }

    /**
     * Test attribute "routing"
     */
    public function testPropertyRouting()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }
}
