<?php
/**
 * CustomerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server Payment API
 *
 * RESTful API for payments via optile Open Payment Gateway (OPG) for server to server communication. Calls to this API require authorization.  ## Current version   * API service version: `1.1.289`   * API model version: `1.20.87`
 *
 * OpenAPI spec version: 1.1.289
 * Contact: support@optile.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optile;

/**
 * CustomerTest Class Doc Comment
 *
 * @category    Class
 * @description Information about customer.
 * @package     Optile
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Customer"
     */
    public function testCustomer()
    {
    }

    /**
     * Test attribute "account_info"
     */
    public function testPropertyAccountInfo()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "delivery_email"
     */
    public function testPropertyDeliveryEmail()
    {
    }

    /**
     * Test attribute "birthday"
     */
    public function testPropertyBirthday()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "phones"
     */
    public function testPropertyPhones()
    {
    }

    /**
     * Test attribute "registration"
     */
    public function testPropertyRegistration()
    {
    }

    /**
     * Test attribute "identities"
     */
    public function testPropertyIdentities()
    {
    }
}
