<?php
/**
 * OperationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server Payment API
 *
 * RESTful API for payments via optile Open Payment Gateway (OPG) for server to server communication. Calls to this API require authorization.  ## Current version   * API service version: `1.1.289`   * API model version: `1.20.87`
 *
 * OpenAPI spec version: 1.1.289
 * Contact: support@optile.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optile;

/**
 * OperationTest Class Doc Comment
 *
 * @category    Class
 * @description Operation
 * @package     Optile
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OperationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Operation"
     */
    public function testOperation()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "auto_registration"
     */
    public function testPropertyAutoRegistration()
    {
    }

    /**
     * Test attribute "allow_recurrence"
     */
    public function testPropertyAllowRecurrence()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "encrypted_account"
     */
    public function testPropertyEncryptedAccount()
    {
    }

    /**
     * Test attribute "client_info"
     */
    public function testPropertyClientInfo()
    {
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
    }

    /**
     * Test attribute "products"
     */
    public function testPropertyProducts()
    {
    }

    /**
     * Test attribute "checkboxes"
     */
    public function testPropertyCheckboxes()
    {
    }

    /**
     * Test attribute "mandate"
     */
    public function testPropertyMandate()
    {
    }

    /**
     * Test attribute "installment"
     */
    public function testPropertyInstallment()
    {
    }

    /**
     * Test attribute "routes"
     */
    public function testPropertyRoutes()
    {
    }

    /**
     * Test attribute "final_operation"
     */
    public function testPropertyFinalOperation()
    {
    }

    /**
     * Test attribute "provider_request"
     */
    public function testPropertyProviderRequest()
    {
    }

    /**
     * Test attribute "preselection"
     */
    public function testPropertyPreselection()
    {
    }

    /**
     * Test attribute "risk_data"
     */
    public function testPropertyRiskData()
    {
    }
}
