<?php
/**
 * StandalonePreselectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server Payment API
 *
 * RESTful API for payments via optile Open Payment Gateway (OPG) for server to server communication. Calls to this API require authorization.  ## Current version   * API service version: `1.1.289`   * API model version: `1.20.87`
 *
 * OpenAPI spec version: 1.1.289
 * Contact: support@optile.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optile;

/**
 * StandalonePreselectionTest Class Doc Comment
 *
 * @category    Class
 * @description The preselection settings influence the resulted payment network and steer its behavior (like deferral) during stand-alone operation.
 * @package     Optile
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StandalonePreselectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StandalonePreselection"
     */
    public function testStandalonePreselection()
    {
    }

    /**
     * Test attribute "deferral"
     */
    public function testPropertyDeferral()
    {
    }

    /**
     * Test attribute "network_codes"
     */
    public function testPropertyNetworkCodes()
    {
    }

    /**
     * Test attribute "challenge_indicator"
     */
    public function testPropertyChallengeIndicator()
    {
    }
}
