<?php
/**
 * StyleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server Payment API
 *
 * RESTful API for payments via optile Open Payment Gateway (OPG) for server to server communication. Calls to this API require authorization.  ## Current version   * API service version: `1.1.289`   * API model version: `1.20.87`
 *
 * OpenAPI spec version: 1.1.289
 * Contact: support@optile.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Optile;

/**
 * StyleTest Class Doc Comment
 *
 * @category    Class
 * @description Allows to change default appearance of payment page. It applies to either hosted payment page (for &#x60;HOSTED&#x60; integration type), or to the page rendered by &#x60;op-payment-widget&#x60; (see AJAX integration topic).
 * @package     Optile
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StyleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Style"
     */
    public function testStyle()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "theme"
     */
    public function testPropertyTheme()
    {
    }

    /**
     * Test attribute "css_override"
     */
    public function testPropertyCssOverride()
    {
    }

    /**
     * Test attribute "client"
     */
    public function testPropertyClient()
    {
    }

    /**
     * Test attribute "resolution"
     */
    public function testPropertyResolution()
    {
    }

    /**
     * Test attribute "hosted_version"
     */
    public function testPropertyHostedVersion()
    {
    }

    /**
     * Test attribute "challenge_window_size"
     */
    public function testPropertyChallengeWindowSize()
    {
    }
}
