<?php
/**
 * ExpressApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Server Payment API
 *
 * RESTful API for payments via optile Open Payment Gateway (OPG) for server to server communication. Calls to this API require authorization.  ## Current version   * API service version: `1.1.289`   * API model version: `1.20.87`
 *
 * OpenAPI spec version: 1.1.289
 * Contact: support@optile.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Optile;

use \Optile\Configuration;
use \Optile\ApiException;
use \Optile\ObjectSerializer;

/**
 * ExpressApiTest Class Doc Comment
 *
 * @category Class
 * @package  Optile
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExpressApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for confirmExpressPreset
     *
     * Confirm express preset session.
     *
     */
    public function testConfirmExpressPreset()
    {
    }

    /**
     * Test case for createExpressPreset
     *
     * Create express preset session.
     *
     */
    public function testCreateExpressPreset()
    {
    }

    /**
     * Test case for getExpressList
     *
     * Get express checkout networks.
     *
     */
    public function testGetExpressList()
    {
    }

    /**
     * Test case for getExpressPreset
     *
     * Get express preset details.
     *
     */
    public function testGetExpressPreset()
    {
    }

    /**
     * Test case for updateExpressPreset
     *
     * Update express preset session.
     *
     */
    public function testUpdateExpressPreset()
    {
    }
}
